project: SC

name: SC_sweep_test # BoolQ, COPA, WiC, COLA

entity: malmung_team1

program : SC_pipeline.py # BoolQ, COPA, WiC, COLA

method: random # grid, bayes, random

metric :
  name: Best_F1  # wandb.log({"val_loss": validation_loss})
  goal: maximize   # minimize, maximize

parameters:

  lr: # param_name, param name =x
    values: [1e-5, 2e-5, 3e-5, 4e-5, 5e-5, 9e-6, 8e-6, 7e-6, 6e-6]

  weight_decay:
    values: [0.1, 0.01, 0.001, 0.0001]

  batch_size:
    values: [64]

  LS:
    values: [0.0, 0.1, 0.01, 0.001]

  seed:
    distribution: int_uniform
    max: 1000
    min: 1

  kfold:
    values: [1, 2, 3]



command:
  - ${env}
  - python
  - ${program}
  - "--epochs"
  - 1000
  - "--name"
  - "sweep"
  - --pretrained
  - "kykim/electra-kor-base"
  - --nsplit
  - 3
  - "--save=1"
  - ${args}


# CUDA_VISIBLE_DEVICES=1 wandb agent malmung_team1/CD/06cs1yg8
# CUDA_VISIBLE_DEVICES=1 wandb agent malmung_team1/SC/1qz0sebl